name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup Go
      uses: actions/setup-go@v5
    - name: version of Go
      run: go version
    - name: install dependencies
      run: go mod tidy
    - name: run tests
      run: |
        go test ./ast -v
        go test ./lexer -v
        go test ./object -v
        go test ./parser -v
        go test ./token -v
